# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:9.6
    restart: always
    ports:
      - 5432:5432
#    network_mode: "host"
    environment:
      POSTGRES_PASSWORD: stand
    volumes:
      - /my/own/datadir:/var/lib/postgresql/data

  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    network_mode: "host"
    volumes:
#        - 'rabbitmq_data:/bitnami'
      - ./path/to/rabbitmq-persistence:/bitnami

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    network_mode: "host"
    volumes:
      - ./path/to/redis-persistence:/bitnami/redis/data
#    networks:
#      - app-tier

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example